version: '3'
joomla:
  container_name: myjoomla
  restart: always
  image: joomla
  environment:
    - MYSQL_PORT_3306_TCP=3306
    - JOOMLA_DB_HOST=myjoomladb
    - JOOMLA_DB_PASSWORD=joomla_secret
    - JOOMLA_DB_NAME=joomla
  ports:
    - 80:80
  volumes:
    - ./html:/var/www/html
  links:
    - joomladb:mysql
joomladb:
  container_name: myjoomladb
  restart: always
  image: mysql:5.7
  environment:
      - MYSQL_ROOT_PASSWORD=joomla_secret
  volumes:
      - ./mysql:/var/lib/mysql
